/**
 * Copyright 2020 Rafael Fernández López <ereslibre@ereslibre.es>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 **/

package constants

// Code generated by release-gen script. DO NOT EDIT.

const (
	// RawReleaseData represents the supported versions for this release
	RawReleaseData = `version: "20.05.0-alpha12"
consoleVersion: "20.05.0-alpha3"
defaultKubernetesVersion: "1.18.2"
kubernetesVersions:
- version: "1.15.12"
  etcdVersion: "3.4.3"
  coreDNSVersion: "1.3.1"
- version: "1.16.9"
  etcdVersion: "3.4.3"
  coreDNSVersion: "1.6.2"
- version: "1.17.5"
  etcdVersion: "3.4.3"
  coreDNSVersion: "1.6.7"
- version: "1.18.2"
  etcdVersion: "3.4.3"
  coreDNSVersion: "1.6.7"
- version: "1.19.0-alpha.3"
  etcdVersion: "3.4.3"
  coreDNSVersion: "1.6.7"`
)
