name: CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        git fetch --prune --unshallow --tags
    - name: Build
      run: |
        nix-shell --pure --run "make oi-binaries"

  unit_and_integration_tests:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        git fetch --prune --unshallow --tags
    - name: Test
      run: |
        nix-shell --pure --run "make test"

  e2e_tests_with_local_CRI_endpoints:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        git fetch --prune --unshallow --tags
    - name: Test
      run: |
        nix-shell --pure --run "make e2e"

  e2e_tests_with_remote_CRI_endpoints:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        git fetch --prune --unshallow --tags
    - name: Test
      run: |
        nix-shell --pure --run "make e2e-remote"
